# Generated by Django 6.0.3 on 2026-03-17 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=150)),
                ('content_type', models.CharField(max_length=150)),
                ('tone', models.CharField(max_length=150)),
                ('target_audience', models.CharField(max_length=255)),
                ('key_message', models.TextField()),
                ('generated_text', models.TextField()),
                ('hashtags', models.JSONField(default=list)),
                ('best_time', models.CharField(max_length=255)),
                ('engagement_score', models.IntegerField()),
                ('tips', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_contents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
